### PR TITLE
Some stuff

### PR DESCRIPTION
**Pull request by why7e**
and more stuff.

Check it

### CODE REVIEW

**Comment by hanyuone** [comment]
Can you give me your contact (in some way)? I need to talk about something.

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot @DerpfacePython  Hi Gabe, your login pages are looking very nice. I have a login and registration update coming soon.

**Comment by why7e** [comment]
@Cyber-Shadow Thanks! Got it. Have you seen my live demo? 

@DerpfacePython, Sir_Lagsalot. Avatar should be a meme.

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot I assume your one is login2? Yea its nice and animated...

@DerpfacePython, @Sir-Lagsalot Logins are done, having trouble with registration.

**Pull request merged**
