### PR TITLE
Merge w/ stuff

### PR DESCRIPTION
**Pull request by why7e**
Made a couple of changes. 
- Animated button
- Installed a V-Env
- Procfile and stuff

It's now hosted on heroku! Automatic updates 'n stuff. You can find them here, at [falconsnest.cf](url) or [falconsnest.herokuapp.com](url)

### CODE REVIEW

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot 
Ahh Cool! You managed to get the server up...
Are you planing to host the server on Heroku permanently ?
Back end access would be nice...
We can save hassle by just using the server setup we have now.

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot Make sure to have DEBUG = False 
And change Secret_Key to a long string of characters

**Comment by why7e** [comment]
Heroku Free Tier has a 30 minute sleep time, after which the program will sleep and the site will take about 10 seconds to boot up. Not that bad. We can just buy a domain and we're good to go.

Will keep debug as false for now, as we're still in development. Dunno where to find the Secret_Key.

You want to bother with a captcha? 

P.S. Take a look at my pull. It clashes with the existing bootstrap, but it looks much better.

**Comment by Cyber-Shadow** [comment]
@Sir-Lagsalot  I was wondering if we have full back end access, including the console + SSL

**Comment by why7e** [comment]
Can we discuss on the issue I made? I can't be bothered to go to my email to check this xD

Don't think we have console access, but all the backend files are on github. If you
You need to change anything, then just push something onto my repo. Heroku automatically redeploys after each commit.

Thinking of removing the header (check falconsnest.cf), Just dunno how. I've come up with a way, but it's not the most elegant, just clearing the header.html file. But im also thinking of the header.html holding The icon and the title, and the login.html for the login.

**Pull request merged**
